apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr
  labels:
    app: dispatcharr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      containers:
      - name: dispatcharr
        image: ghcr.io/dispatcharr/dispatcharr:latest
        ports:
        - containerPort: 9191
        volumeMounts:
        - name: dispatcharr-data
          mountPath: /data
        env:
        - name: DISPATCHARR_ENV
          value: "aio"
        - name: REDIS_HOST
          value: "localhost"
        - name: CELERY_BROKER_URL
          value: "redis://localhost:6379/0"
        - name: DISPATCHARR_LOG_LEVEL
          value: "info"
      volumes:
      - name: dispatcharr-data
        persistentVolumeClaim:
          claimName: dispatcharr-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcharr-service
  labels:
    app: dispatcharr
spec:
  type: LoadBalancer
  ports:
  - port: 9191
    targetPort: 9191
    protocol: TCP
  selector:
    app: dispatcharr
