apiVersion: v1
kind: Namespace
metadata:
  name: robert-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: requestrr-pvc
  namespace: robert-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # This is k3s's default storage class
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestrr
  namespace: robert-prod
  labels:
    app: requestrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestrr
  template:
    metadata:
      labels:
        app: requestrr
    spec:
      containers:
      - name: requestrr
        image: darkalfx/requestrr
        ports:
        - containerPort: 4545
        volumeMounts:
        - name: config
          mountPath: /root/config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: requestrr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: requestrr
  namespace: robert-prod
  annotations:
    service.beta.kubernetes.io/external-traffic-policy: Local
spec:
  type: LoadBalancer
  ports:
  - port: 4545
    targetPort: 4545
    protocol: TCP
  selector:
    app: requestrr
