apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: movies-volume
              mountPath: /movies
            - name: tv-volume
              mountPath: /tv
          ports:
            - containerPort: 6767
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: movies-volume
          persistentVolumeClaim:
            claimName: plex-data-movies-nfs-pvc
        - name: tv-volume
          persistentVolumeClaim:
            claimName: plex-data-series-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  selector:
    app: bazarr
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767
  type: LoadBalancer
---
